#!/bin/bash
# -----------------------------------------------------------------------------
# Telemetry Platform — Deployment Orchestrator
#
# Builds and starts the full stack using Docker Compose. Intended for both
# manual operator runs on a local workstation and automated invocation via
# systemd on EC2 production nodes.
#
# Environment configuration is resolved automatically:
#   • Local:  uses infrastructure/.env when present.
#   • EC2:    fetches secrets from AWS SSM Parameter Store when .env is absent.
# -----------------------------------------------------------------------------

set -euo pipefail

# Resolve repository and infrastructure paths relative to this script.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
COMPOSE_BASE="${SCRIPT_DIR}/docker-compose.yml"
COMPOSE_PROD="${SCRIPT_DIR}/docker-compose.prod.yml"

SSM_READ_KEY_PATH="/telemetry/prod/READ_API_KEY"
SSM_WRITE_KEY_PATH="/telemetry/prod/WRITE_API_KEY"

fetch_ssm_secret() {
  local param_name="$1"
  local result

  if ! result="$(aws ssm get-parameter \
    --name "${param_name}" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text 2>&1)"; then
    echo "${result}" >&2
    return 1
  fi

  if [[ -z "${result}" || "${result}" == "None" ]]; then
    echo "Parameter ${param_name} returned an empty value." >&2
    return 1
  fi

  printf '%s' "${result}"
}

# -----------------------------------------------------------------------------
# Environment resolution — local .env file or AWS SSM Parameter Store
# -----------------------------------------------------------------------------
if [[ -f "${ENV_FILE}" ]]; then
  echo "Local .env file detected. Proceeding with deployment."
else
  echo "No .env file found. Attempting to fetch keys from AWS SSM Parameter Store..."

  if ! command -v aws >/dev/null 2>&1; then
    echo "CRITICAL: AWS CLI is not installed. Cannot retrieve secrets from SSM." >&2
    exit 1
  fi

  SSM_ERROR=""
  if ! READ_API_KEY="$(fetch_ssm_secret "${SSM_READ_KEY_PATH}")"; then
    SSM_ERROR="Failed to retrieve ${SSM_READ_KEY_PATH}."
  elif ! WRITE_API_KEY="$(fetch_ssm_secret "${SSM_WRITE_KEY_PATH}")"; then
    SSM_ERROR="Failed to retrieve ${SSM_WRITE_KEY_PATH}."
  fi

  if [[ -n "${SSM_ERROR}" ]]; then
    echo "CRITICAL: Failed to retrieve API keys from AWS SSM Parameter Store." >&2
    echo "          Verify the instance IAM role grants ssm:GetParameter on:" >&2
    echo "            ${SSM_READ_KEY_PATH}" >&2
    echo "            ${SSM_WRITE_KEY_PATH}" >&2
    echo "          Detail: ${SSM_ERROR}" >&2
    exit 1
  fi

  cat > "${ENV_FILE}" <<EOF
# API keys: Read for GET, Write for POST
# Auto-generated by deploy.sh from AWS SSM Parameter Store
READ_API_KEY=${READ_API_KEY}
WRITE_API_KEY=${WRITE_API_KEY}
EOF

  chmod 600 "${ENV_FILE}"
  echo "Successfully generated ${ENV_FILE} from SSM parameters."
fi

# -----------------------------------------------------------------------------
# Pre-flight checks and stack deployment
# -----------------------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: Docker is not installed or not on PATH." >&2
  exit 1
fi

export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-sensor-platform}"

echo "Deploying telemetry stack from ${SCRIPT_DIR}..."

docker compose \
  --env-file "${ENV_FILE}" \
  -f "${COMPOSE_BASE}" \
  -f "${COMPOSE_PROD}" \
  up -d --build --remove-orphans

echo "Deployment complete. Verify containers with: docker compose -f ${COMPOSE_BASE} ps"
